const { Octokit } = require('@octokit/rest');

async function createFixPR(accessToken, owner, repo, scanResults) {
  const octokit = new Octokit({ auth: accessToken });
  const branchName = `grassion-fix-${Date.now()}`;

  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  const { data: ref } = await octokit.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
  await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: ref.object.sha });

  for (const result of scanResults) {
    if (result.fixedCode) {
      const { data: fileData } = await octokit.repos.getContent({ owner, repo, path: result.file });
      await octokit.repos.createOrUpdateFileContents({
        owner, repo, path: result.file,
        message: `fix: add auth middleware to ${result.file}`,
        content: Buffer.from(result.fixedCode).toString('base64'),
        sha: fileData.sha,
        branch: branchName
      });
    }
  }

  const issueCount = scanResults.reduce((sum, r) => sum + r.issues.length, 0);
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `🛡️ Grassion: Fix ${issueCount} auth gap${issueCount > 1 ? 's' : ''}`,
    body: `## Security Fix by Grassion\n\nFound and fixed **${issueCount} unprotected API endpoint${issueCount > 1 ? 's' : ''}**.\n\n### Files Fixed:\n${scanResults.map(r => `- \`${r.file}\` — ${r.issues.length} issue${r.issues.length > 1 ? 's' : ''}`).join('\n')}\n\n---\n*Auto-generated by [Grassion](https://grassion.com) — Zero-Touch Codebase Security*`,
    head: branchName,
    base: defaultBranch
  });

  return pr;
}

module.exports = { createFixPR };
