import { describe, it, expect } from 'vitest'
import { detectAI } from './ai-detection.js'

const base = {
  title: 'chore: update deps',
  additions: 0,
  deletions: 0,
  changedFiles: 0,
  commitCount: 1,
  openedAt: null,
  mergedAt: null,
  reviewCount: 0,
}

describe('detectAI', () => {
  it('detects copilot from co-author trailer', () => {
    const r = detectAI({
      ...base,
      body: null,
      labels: [],
      commits: [
        {
          message: 'feat: add login\n\nCo-authored-by: Copilot <Copilot@users.noreply.github.com>',
          author: { name: 'human', email: 'h@x.com' },
        },
      ],
    })
    expect(r.source).toBe('copilot')
    expect(r.method).toBe('trailer')
    expect(r.confidence).toBeCloseTo(0.95)
  })

  it('detects claude from co-author trailer', () => {
    const r = detectAI({
      ...base,
      body: null,
      labels: [],
      commits: [
        {
          message: 'fix: bug\n\nCo-authored-by: Claude <noreply@anthropic.com>',
          author: { name: 'h', email: 'h@x.com' },
        },
      ],
    })
    expect(r.source).toBe('claude')
    expect(r.method).toBe('trailer')
  })

  it('manual label overrides trailer detection', () => {
    const r = detectAI({
      ...base,
      body: null,
      labels: ['grassion:human'],
      commits: [
        {
          message: 'Co-authored-by: Copilot <Copilot@users.noreply.github.com>',
          author: { name: 'h', email: 'h@x.com' },
        },
      ],
    })
    expect(r.source).toBe(null)
    expect(r.method).toBe('label')
    expect(r.confidence).toBe(1)
  })

  it('grassion:ai-cursor label tags as cursor', () => {
    const r = detectAI({ ...base, body: null, labels: ['grassion:ai-cursor'], commits: [] })
    expect(r.source).toBe('cursor')
  })

  it('detects from PR body regex', () => {
    const r = detectAI({
      ...base,
      body: 'This was generated by Cursor in about 30 minutes.',
      labels: [],
      commits: [],
    })
    expect(r.source).toBe('cursor')
    expect(r.method).toBe('body_regex')
    expect(r.confidence).toBeCloseTo(0.7)
  })

  it('returns null source when no signals', () => {
    const r = detectAI({
      ...base,
      body: 'Standard PR description with no AI mention.',
      labels: ['enhancement'],
      commits: [{ message: 'fix typo', author: { name: 'h', email: 'h@x.com' } }],
    })
    expect(r.source).toBe(null)
    expect(r.confidence).toBe(0)
  })

  describe('statistical_pattern (priority 4)', () => {
    const now = new Date('2024-01-15T10:00:00Z')
    const mergedIn2h = new Date('2024-01-15T12:00:00Z')
    const mergedIn3h = new Date('2024-01-15T13:00:00Z')

    it('4a fires for bulk generation pattern', () => {
      const r = detectAI({
        ...base,
        title: 'add feature',
        body: null,
        labels: [],
        commits: [],
        additions: 250,
        deletions: 10,
        changedFiles: 3,
        openedAt: now,
        mergedAt: mergedIn3h,
      })
      expect(r.source).toBe('unknown_ai')
      expect(r.method).toBe('statistical_pattern')
      expect(r.confidence).toBeCloseTo(0.45)
    })

    it('4a does not fire when changedFiles > 5', () => {
      const r = detectAI({
        ...base,
        title: 'add feature',
        body: null,
        labels: [],
        commits: [],
        additions: 250,
        deletions: 10,
        changedFiles: 8,
        commitCount: 5,
        openedAt: now,
        mergedAt: mergedIn3h,
      })
      expect(r.source).toBe(null)
    })

    it('4b fires for single-commit large write', () => {
      const r = detectAI({
        ...base,
        title: 'add feature',
        body: null,
        labels: [],
        commits: [],
        commitCount: 1,
        additions: 200,
        deletions: 5,
      })
      expect(r.source).toBe('unknown_ai')
      expect(r.method).toBe('statistical_pattern')
      expect(r.confidence).toBeCloseTo(0.40)
    })

    it('4c fires for conventional commit + large + no review + fast merge', () => {
      const r = detectAI({
        ...base,
        title: 'feat(auth): add OAuth flow',
        body: null,
        labels: [],
        commits: [],
        additions: 150,
        reviewCount: 0,
        openedAt: now,
        mergedAt: mergedIn2h,
      })
      expect(r.source).toBe('unknown_ai')
      expect(r.method).toBe('statistical_pattern')
      expect(r.confidence).toBeCloseTo(0.35)
    })

    it('4c does not fire when reviewCount > 0', () => {
      const r = detectAI({
        ...base,
        title: 'feat(auth): add OAuth flow',
        body: null,
        labels: [],
        commits: [],
        additions: 150,
        reviewCount: 1,
        openedAt: now,
        mergedAt: mergedIn2h,
      })
      expect(r.source).toBe(null)
    })

    it('label takes priority over statistical pattern', () => {
      const r = detectAI({
        ...base,
        title: 'feat: big write',
        body: null,
        labels: ['grassion:ai-copilot'],
        commits: [],
        commitCount: 1,
        additions: 300,
        deletions: 5,
      })
      expect(r.method).toBe('label')
      expect(r.source).toBe('copilot')
    })
  })
})
