import { describe, it, expect } from 'vitest'
import { detectAI } from './ai-detection.js'

describe('detectAI', () => {
  it('detects copilot from co-author trailer', () => {
    const r = detectAI({
      body: null,
      labels: [],
      commits: [
        {
          message: 'feat: add login\n\nCo-authored-by: Copilot <Copilot@users.noreply.github.com>',
          author: { name: 'human', email: 'h@x.com' },
        },
      ],
    })
    expect(r.source).toBe('copilot')
    expect(r.method).toBe('trailer')
    expect(r.confidence).toBeCloseTo(0.95)
  })

  it('detects claude from co-author trailer', () => {
    const r = detectAI({
      body: null,
      labels: [],
      commits: [
        {
          message: 'fix: bug\n\nCo-authored-by: Claude <noreply@anthropic.com>',
          author: { name: 'h', email: 'h@x.com' },
        },
      ],
    })
    expect(r.source).toBe('claude')
    expect(r.method).toBe('trailer')
  })

  it('manual label overrides trailer detection', () => {
    const r = detectAI({
      body: null,
      labels: ['grassion:human'],
      commits: [
        {
          message: 'Co-authored-by: Copilot <Copilot@users.noreply.github.com>',
          author: { name: 'h', email: 'h@x.com' },
        },
      ],
    })
    expect(r.source).toBe(null)
    expect(r.method).toBe('label')
    expect(r.confidence).toBe(1)
  })

  it('grassion:ai-cursor label tags as cursor', () => {
    const r = detectAI({ body: null, labels: ['grassion:ai-cursor'], commits: [] })
    expect(r.source).toBe('cursor')
  })

  it('detects from PR body regex', () => {
    const r = detectAI({
      body: 'This was generated by Cursor in about 30 minutes.',
      labels: [],
      commits: [],
    })
    expect(r.source).toBe('cursor')
    expect(r.method).toBe('body_regex')
    expect(r.confidence).toBeCloseTo(0.7)
  })

  it('returns null source when no signals', () => {
    const r = detectAI({
      body: 'Standard PR description with no AI mention.',
      labels: ['enhancement'],
      commits: [{ message: 'fix typo', author: { name: 'h', email: 'h@x.com' } }],
    })
    expect(r.source).toBe(null)
    expect(r.confidence).toBe(0)
  })
})
